# このファイルは開発環境用のオーバーライド設定です
# docker compose up 時に自動的に読み込まれます

services:
  web:
    # 開発環境では環境変数を上書き
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000

    # 開発用のボリュームマウント
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next

    # 開発用のポート設定（ホットリロード用）
    ports:
      - "3000:3000"

    # 開発環境では読み取り専用ファイルシステムを無効化
    read_only: false

    # 開発用のコマンド
    command: pnpm dev
